### Login
POST {{host}}/api/login
Content-Type: application/json

{
  "username": "johan",
  "password": "secret01!"
}


### Register a user
POST {{host}}/api/register
Content-Type: application/json

{
  "username": "johan",
  "password": "secret01!",
  "email": "johan@johan.nl"
}


### Get all users
GET {{host}}/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwMDMyNDIyMSwiZXhwIjoxNzAwMzMxNDIxfQ.Qilgg12BaPvqjrQWxuRcGYM4_n_t_4QK1Pr5JulqqMNtN6Zlo-JZMRmFejQrrsEU79Zp-Iof5EuqeDddviavot95Z15GsNrsRUMQ_YEwjuwxKHYd9yA8raNjIoOjj47KkFGzHhPTV08Q5d47jll3M26KaGPZFqlZxg3doj78Ldl_mEJ8PMs9cAgXWazHGgsXqHWcZpeGv5gH71GIB6z9rDYDk_QICo2f3XjrhHIOaj6o2u_j3NQXSo151JJ49e3D9ShJX97fOuyf0Z7JD80bWTxGISc7oF9d0Ki1Mbc8V_2tzkVeYQs7quaZOqir42pkwMfGYQFcRWakIiJlS0cS94oW3qBZRPZXwDqws3coZDk-3iSzJBDIBa3HHjylnzRaBcVDyuro4dPiw3oP80ElKzDrrHTlFJsAUMs5VADGdLUs_UoEnzKMBKNxF8N3Wu6ZypRr71vSM7UKC7N9kOFFV3cpsUE1l4OuWJNL80l9gNu3LzaDGk9OTA5zIoRjzToKSJytvpnC6vZ8ScrnBO6UiqYD9pef5vxOyCunVN_ntaQ_pd-1XZNTWPmQBD-spuz6D-wOSbNK0Ckgee252KrmHWQP0FHjvhCFEc43-7SSFAtAskAosfE-vpRxZiEnkuBqwyupvCVaT3xaeG1LAYmy-c7psyh7i5NF670fpWg2vsI